using './main.bicep'

param environment = 'canary'
param namePrefix = 'travel-assistant'
param containerAppsEnvironmentId = '/subscriptions/{sub}/resourceGroups/travel-assistant-canary-rg/providers/Microsoft.App/managedEnvironments/travel-assistant-cae-canary'
param canaryKeyVaultId = '/subscriptions/{sub}/resourceGroups/travel-assistant-canary-rg/providers/Microsoft.KeyVault/vaults/travel-assistant-kv-canary'
param canaryKeyVaultUri = 'https://travel-assistant-kv-canary.vault.azure.net/'
param applicationInsightsId = '/subscriptions/{sub}/resourceGroups/travel-assistant-canary-rg/providers/Microsoft.Insights/components/travel-assistant-ai-canary'
param applicationInsightsConnectionString = '__SET_VIA_ENV_OR_KEYVAULT__'
param logAnalyticsWorkspaceId = '/subscriptions/{sub}/resourceGroups/travel-assistant-canary-rg/providers/Microsoft.OperationalInsights/workspaces/travel-assistant-law-canary'
param checkoutApiBaseUrl = 'https://api-canary.travel-assistant.example.com'
param canaryRunnerImage = 'travelassistantacr.azurecr.io/canary-runner:v1.0.0'
param pagerDutyP1ActionGroupId = '/subscriptions/{sub}/resourceGroups/travel-assistant-shared-rg/providers/Microsoft.Insights/actionGroups/pd-p1'
param pagerDutyP2ActionGroupId = '/subscriptions/{sub}/resourceGroups/travel-assistant-shared-rg/providers/Microsoft.Insights/actionGroups/pd-p2'
param pagerDutyP3ActionGroupId = '/subscriptions/{sub}/resourceGroups/travel-assistant-shared-rg/providers/Microsoft.Insights/actionGroups/pd-p3'
